### ISSUE TITLE
no such file or directory error

### ISSUE THREAD

**Issue by somiyaa** [chestnut3108/SENTIMENT-ANALYSIS-ON-AUDIO#1]
![image](https://user-images.githubusercontent.com/29824578/28838100-decdeac4-770c-11e7-9d89-5589d56d345a.png)

can you please tell whats wrong here ? I am new to python. please help.

**Comment by shivam-singhl** [comment]
Hello Somiyaa,
         I have fixed the problem clone the repository again....or just
copy all the pickle files from the PICKLE FILES into your current working
directory..

Regards Shivam

**Comment by somiyaa** [comment]
Hello Shivam

I am getting the same error after cloning the repository again. what else can i do to resolve this issue ?

**Comment by shivam-singhl** [comment]
Its all fixed now....run the audio.py to run the program.
