### ISSUE TITLE
Warnings and inaccurate output

### ISSUE THREAD

**Issue by rmohan19883** [chestnut3108/SENTIMENT-ANALYSIS-ON-AUDIO#3]
Dear Sir,
Thanks for uploading the code.
I tried it , with "How is it going" and it gave me a "neg" output .. not sure if that is accurate - Can you please check? 
Also I got loads of warning on "unpickle .. "  not clear if these warnings are interfering with the results/logic ...

Below is the complete  log ->

python 3.7.3 (default, Jun 19 2019, 07:38:49) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable. Visit
http://www.python.org/download/mac/tcltk/ for current information.
>>> 
 RESTART: /Users/rakeshmohan/Downloads/SENTIMENT-ANALYSIS-ON-AUDIO-master/AUDIO SCRIPT.py 

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator DictVectorizer from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator MultinomialNB from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator BernoulliNB from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator LinearSVC from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator SGDClassifier from version pre-0.18 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
3.7.3 (default, Jun 19 2019, 07:38:49) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Say something!
hello how's it going
('neg', 1.0)
>>>

**Comment by shivam-singhl** [comment]
Hi Rakesh the classifier may not be accurately trained or dataset may be ambiguous thats why it is giving such output. For the loads of warning that you are getting please ignore them.
